dev(all): use symbol.industries for maven

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -581,6 +581,10 @@ jobs:
             echo "missing MAVEN_GPG_PASSPHRASE secret"
             exit 1
           fi
+          if [ -z "${MAVEN_GPG_KEY_ID}" ]; then
+            echo "missing MAVEN_GPG_KEY_ID variable"
+            exit 1
+          fi
           if [ -z "${RUBYGEMS_API_KEY}" ]; then
             echo "missing RUBYGEMS_API_KEY secret"
             exit 1
@@ -615,6 +619,7 @@ jobs:
           MAVEN_REPOSITORY_PASSWORD: ${{ secrets.MAVEN_REPOSITORY_PASSWORD }}
           MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
           MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
+          MAVEN_GPG_KEY_ID: ${{ vars.MAVEN_GPG_KEY_ID }}
           RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
           HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
           PUB_DEV_CREDENTIALS_JSON: ${{ secrets.PUB_DEV_CREDENTIALS_JSON }}
@@ -642,6 +647,7 @@ jobs:
           MAVEN_REPOSITORY_PASSWORD: ${{ secrets.MAVEN_REPOSITORY_PASSWORD }}
           MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
           MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
+          MAVEN_GPG_KEY_ID: ${{ vars.MAVEN_GPG_KEY_ID }}
           RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
           HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
           PUB_DEV_CREDENTIALS_JSON: ${{ secrets.PUB_DEV_CREDENTIALS_JSON }}
